name: deploy dev to stg

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download a file
      run: wget https://github.com/EugeneKrapivin/gigman.cli/files/10148496/gigman.zip -O gigman.zip
    - name: Extract gigman
      run: 7z x gigman.zip
    - name: apply gigman
      run: gigman site apply 
