name: deploy dev to stg

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download gigman
      run: wget https://github.com/EugeneKrapivin/gigman.cli/files/10148496/gigman.zip -O gigman.zip
    - name: Extract gigman
      run: 7z x gigman.zip
    - name: Make gigman executable
      run: chmod +x gigman
    - name: create gigman context
      run: ./gigman context create -u ${{secrets.GIGMAN_USERKEY}} -s ${{secrets.GIGMAN_SECRET}} -n gha
    - name: set gigman context
      run: ./gigman context set -n gha
    - name: Apply gigman
      run: ./gigman site apply 
